# ********RoostGPT********

# Test generated by RoostGPT for test karate-adp using AI Type Claude AI and AI Model claude-3-7-sonnet-20250219
# 
# Feature file generated for /hr/v2/workers_get for http method type GET 
# RoostTestHash=3a0d8b55f2
# 
# 

# ********RoostGPT********
Feature: Test Worker API Endpoints

  Background:
    * def urlBase = karate.properties['url1_adp_URL_BASE'] || karate.get('urlBase', 'http://localhost:4010')
    * def authToken = karate.properties['url1_adp_AUTH_TOKEN']

  Scenario: Get all workers successfully
    Given url urlBase
    And path '/hr/v2/workers'
    And header Authorization = authToken
    When method GET
    Then status 200
    And match header Cache-Control == '#present'
    And match header sm_transactionid == '#present'
    And match header Content-Type contains 'application/json'
    And match response == { workers: '#array' }
    And match each response.workers[*] contains { workerID: { idValue: '#string', schemeCode: { codeValue: '#string', shortName: '#string' } } }
    And match each response.workers[*].associateOID == '#string'
    And match each response.workers[*].workerStatus.statusCode.codeValue == '#string'
    And match each response.workers[*].workerStatus.statusCode.shortName == '#string'
    And match each response.workers[*].person.legalName.familyName1 == '#string'
    And match each response.workers[*].person.legalName.givenName == '#string'
    And match each response.workers[*].person.legalName.formattedName == '#string'
    And match each response.workers[*].person.birthDate == '#string'
    And match each response.workers[*].person.genderCode.codeValue == '#string'

  Scenario Outline: Get workers with filter parameter
    Given url urlBase
    And path '/hr/v2/workers'
    And param $filter = '<filter>'
    And header Authorization = authToken
    When method GET
    Then status 200
    And match header Content-Type contains 'application/json'
    And match response == { workers: '#array' }

    Examples:
      | read('hr_v2_workers_get.csv') |

  Scenario Outline: Get workers with pagination parameters
    Given url urlBase
    And path '/hr/v2/workers'
    And param $top = <top>
    And param $skip = <skip>
    And header Authorization = authToken
    When method GET
    Then status 200
    And match header Content-Type contains 'application/json'
    And match response == { workers: '#array' }

    Examples:
      | read('hr_v2_workers_get.csv') |

  Scenario: Get workers with count parameter
    Given url urlBase
    And path '/hr/v2/workers'
    And param $count = true
    And header Authorization = authToken
    When method GET
    Then status 200
    And match header Content-Type contains 'application/json'
    And match response == { workers: '#array' }

  Scenario: Get workers with multiple parameters
    Given url urlBase
    And path '/hr/v2/workers'
    And param $filter = "/workers/workerID/idValue eq '51104-10'"
    And param $top = 5
    And param $skip = 0
    And param $count = true
    And header Authorization = authToken
    When method GET
    Then status 200
    And match header Content-Type contains 'application/json'
    And match response == { workers: '#array' }

  Scenario: Get workers with invalid authorization
    Given url urlBase
    And path '/hr/v2/workers'
    And header Authorization = 'invalid-token'
    When method GET
    Then status 401
    And match response.message == '#string'

  Scenario: Get workers with invalid filter parameter
    Given url urlBase
    And path '/hr/v2/workers'
    And param $filter = 'invalid-filter-syntax'
    And header Authorization = authToken
    When method GET
    Then status 400
    And match response.message == '#present'
