# ********RoostGPT********

# Test generated by RoostGPT for test karate-adp using AI Type Claude AI and AI Model claude-3-7-sonnet-20250219
# 
# Feature file generated for /hr/v2/workers_get for http method type GET 
# RoostTestHash=3a0d8b55f2
# 
# 

# ********RoostGPT********
Feature: Worker API Tests

  Background:
    * def urlBase = karate.properties['url1_adp_URL_BASE'] || karate.get('urlBase', 'http://localhost:4010')
    * def authToken = karate.properties['url1_adp_AUTH_TOKEN']

  Scenario: Get all workers successfully
    Given url urlBase
    And path '/hr/v2/workers'
    And header Authorization = authToken
    When method GET
    Then status 200
    And match header Cache-Control == '#present'
    And match header sm_transactionid == '#present'
    And match header Content-Type contains 'application/json'
    And match response == { workers: '#array' }
    And match each response.workers contains
      """
      { 
        workerID: { 
          idValue: '#string', 
          schemeCode: { 
            codeValue: '#string', 
            shortName: '#string' 
          } 
        },
        associateOID: '##string',
        workerStatus: '##object',
        person: '##object',
        businessCommunication: '##object',
        workerDates: '##object',
        workAssignments: '##array'
      }
      """
    And match each response.workers[*].person contains
      """
      {
        legalName: '##object',
        birthDate: '##string',
        genderCode: '##object'
      }
      """
    And match each response.workers[*].person.legalName contains
      """
      {
        familyName1: '##string',
        givenName: '##string',
        formattedName: '##string'
      }
      """

  Scenario Outline: Get workers with filter parameter
    Given url urlBase
    And path '/hr/v2/workers'
    And param $filter = '<filterValue>'
    And header Authorization = authToken
    When method GET
    Then status 200
    And match header Content-Type contains 'application/json'
    And match response == { workers: '#array' }

    Examples:
      | read('hr_v2_workers_get.csv') |

  Scenario Outline: Get workers with pagination parameters
    Given url urlBase
    And path '/hr/v2/workers'
    And param $top = <top>
    And param $skip = <skip>
    And header Authorization = authToken
    When method GET
    Then status 200
    And match header Content-Type contains 'application/json'
    And match response == { workers: '#array' }
    And assert response.workers.length <= <top>

    Examples:
      | read('hr_v2_workers_get.csv') |

  Scenario: Get workers with count parameter
    Given url urlBase
    And path '/hr/v2/workers'
    And param $count = true
    And header Authorization = authToken
    When method GET
    Then status 200
    And match header Content-Type contains 'application/json'
    And match response == { workers: '#array' }

  Scenario: Get workers with multiple query parameters
    Given url urlBase
    And path '/hr/v2/workers'
    And param $filter = '/workers/workerID/idValue eq \'0099\''
    And param $top = 5
    And param $skip = 0
    And param $count = true
    And header Authorization = authToken
    When method GET
    Then status 200
    And match header Content-Type contains 'application/json'
    And match response == { workers: '#array' }
    And assert response.workers.length <= 5

  Scenario: Unauthorized access to workers endpoint
    Given url urlBase
    And path '/hr/v2/workers'
    And header Authorization = 'invalid_token'
    When method GET
    Then status 401
    And match response.message == '#string'

  Scenario: Bad request with invalid filter parameter
    Given url urlBase
    And path '/hr/v2/workers'
    And param $filter = 'invalid_filter_syntax'
    And header Authorization = authToken
    When method GET
    Then status 400
    And match response.message == '#present'
    And match response.message.confirmMessage == '#present'
    And match response.message.confirmMessage.processMessages == '#array'

  Scenario: Server error when retrieving workers
    Given url urlBase
    And path '/hr/v2/workers'
    And header Authorization = authToken
    And header X-Simulate-Error = '500'
    When method GET
    Then status 500
    And match response.message == '#string'
