# ********RoostGPT********

# Test generated by RoostGPT for test karate-adp using AI Type Claude AI and AI Model claude-3-7-sonnet-20250219
# 
# Feature file generated for /hr/v2/workers_get for http method type GET 
# RoostTestHash=3a0d8b55f2
# 
# 

# ********RoostGPT********
Feature: Test Workers API Endpoint

  Background:
    * def urlBase = karate.properties['url1_adp_URL_BASE'] || karate.get('urlBase', 'http://localhost:4010')
    * def authToken = karate.properties['url1_adp_AUTH_TOKEN']

  Scenario: Get all workers successfully
    Given url urlBase
    And path '/hr/v2/workers'
    And header Authorization = authToken
    When method GET
    Then status 200
    And match header Cache-Control == '#present'
    And match header sm_transactionid == '#present'
    And match header Content-Type contains 'application/json'
    And match response == { workers: '#array' }
    And match each response.workers contains
      """
      { 
        workerID: { 
          idValue: '#string', 
          schemeCode: { 
            codeValue: '#string', 
            shortName: '#string' 
          } 
        },
        associateOID: '##string',
        workerStatus: '##object',
        person: '##object',
        businessCommunication: '##object',
        workerDates: '##object',
        workAssignments: '##array'
      }
      """

  Scenario Outline: Get workers with filter parameter
    Given url urlBase
    And path '/hr/v2/workers'
    And param $filter = '<filter>'
    And header Authorization = authToken
    When method GET
    Then status 200
    And match header Content-Type contains 'application/json'
    And match response == { workers: '#array' }

    Examples:
      | read('hr_v2_workers_get.csv') |

  Scenario Outline: Get workers with count parameter
    Given url urlBase
    And path '/hr/v2/workers'
    And param $count = '<count>'
    And header Authorization = authToken
    When method GET
    Then status 200
    And match header Content-Type contains 'application/json'
    And match response == { workers: '#array' }

    Examples:
      | read('hr_v2_workers_get.csv') |

  Scenario Outline: Get workers with pagination parameters
    Given url urlBase
    And path '/hr/v2/workers'
    And param $top = <top>
    And param $skip = <skip>
    And header Authorization = authToken
    When method GET
    Then status 200
    And match header Content-Type contains 'application/json'
    And match response == { workers: '#array' }

    Examples:
      | read('hr_v2_workers_get.csv') |

  Scenario: Get workers with multiple query parameters
    Given url urlBase
    And path '/hr/v2/workers'
    And param $filter = '/workers/workerStatus/statusCode/codeValue eq "Active"'
    And param $top = 5
    And param $skip = 0
    And param $count = true
    And header Authorization = authToken
    When method GET
    Then status 200
    And match header Content-Type contains 'application/json'
    And match response == { workers: '#array' }

  Scenario: Verify worker details in response
    Given url urlBase
    And path '/hr/v2/workers'
    And header Authorization = authToken
    When method GET
    Then status 200
    And match header Content-Type contains 'application/json'
    And match response.workers[0].workerID.idValue == '#string'
    And match response.workers[0].workerID.schemeCode.codeValue == '#string'
    And match response.workers[0].workerID.schemeCode.shortName == '#string'
    And match response.workers[0].person.legalName.givenName == '#string'
    And match response.workers[0].person.legalName.familyName1 == '#string'
    And match response.workers[0].workerStatus.statusCode.codeValue == '#string'
    And match response.workers[0].workerStatus.statusCode.shortName == '#string'

  Scenario: Test unauthorized access
    Given url urlBase
    And path '/hr/v2/workers'
    And header Authorization = 'invalid_token'
    When method GET
    Then status 401
    And match response.message == '#string'

  Scenario: Test bad request with invalid parameters
    Given url urlBase
    And path '/hr/v2/workers'
    And param $filter = 'invalid_filter_syntax'
    And header Authorization = authToken
    When method GET
    Then status 400
    And match response.message == '#present'
