
// ********RoostGPT********
/*
Test generated by RoostGPT for test hebrew-unit-test using AI Type Claude AI and AI Model claude-3-5-sonnet-20241022

ROOST_METHOD_HASH=getProductById_5e209a8195
ROOST_METHOD_SIG_HASH=getProductById_5e209a8195

                                               תרחיש 1: אחזור מוצר קיים לפי מזהה

                                                                          פרטים:
                                               שם הבדיקה: getExistingProductById
            תיאור: בדיקת אחזור מוצר כאשר קיים מוצר עם המזהה המבוקש במאגר הנתונים

                                                                          ביצוע:
                                                                          הכנה:
                                            - יצירת אובייקט Product עם מזהה תקין
                      - הגדרת mock עבור productRepository שיחזיר את המוצר המבוקש
                                                                          פעולה:
                                 - קריאה למתודה getProductById עם המזהה של המוצר
                                                                          בדיקה:
                                 - וידוא שהתקבל ResponseEntity עם סטטוס 200 (OK)
                                         - וידוא שהמוצר שהוחזר תואם למוצר המצופה

                                                                          אימות:
    הבדיקה מוודאת שכאשר קיים מוצר במאגר הנתונים, המערכת מחזירה אותו בהצלחה עם סטטוס תקין

*/

// ********RoostGPT********

package com.bootexample4.products.controller;

import static org.mockito.Mockito.*;
import static org.junit.jupiter.api.Assertions.*;
import java.util.Optional;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import com.bootexample4.products.model.Product;
import com.bootexample4.products.repository.ProductRepository;
import org.junit.jupiter.api.*;
import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

@ExtendWith(MockitoExtension.class)
class ProductControllerGetProductByIdTest {

	@Mock
	private ProductRepository productRepository;

	@InjectMocks
	private ProductController productController;

	private Product testProduct;

	@BeforeEach
	void setUp() {
		testProduct = new Product();
		testProduct.setId(1L);
		testProduct.setName("Test Product");
		testProduct.setDescription("Test Description");
		testProduct.setPrice(99.99);
	}

	@Test
    @Tag("valid")
    void getExistingProductById() {
        when(productRepository.findById(1L)).thenReturn(Optional.of(testProduct));
        ResponseEntity<Product> response = productController.getProductById(1L);
        assertEquals(HttpStatus.OK, response.getStatusCode());
        assertNotNull(response.getBody());
        assertEquals(testProduct.getId(), response.getBody().getId());
        assertEquals(testProduct.getName(), response.getBody().getName());
        assertEquals(testProduct.getDescription(), response.getBody().getDescription());
        assertEquals(testProduct.getPrice(), response.getBody().getPrice());

        verify(productRepository).findById(1L);
    }

	@Test
    @Tag("invalid")
    void getNonExistingProductById() {
        when(productRepository.findById(999L)).thenReturn(Optional.empty());
        ResponseEntity<Product> response = productController.getProductById(999L);
        assertEquals(HttpStatus.NOT_FOUND, response.getStatusCode());
        assertNull(response.getBody());

        verify(productRepository).findById(999L);
    }

	@Test
    @Tag("boundary")
    void getProductByIdZero() {
        when(productRepository.findById(0L)).thenReturn(Optional.empty());
        ResponseEntity<Product> response = productController.getProductById(0L);
        assertEquals(HttpStatus.NOT_FOUND, response.getStatusCode());
        assertNull(response.getBody());

        verify(productRepository).findById(0L);
    }

	@Test
    @Tag("boundary")
    void getProductByNegativeId() {
        when(productRepository.findById(-1L)).thenReturn(Optional.empty());
        ResponseEntity<Product> response = productController.getProductById(-1L);
        assertEquals(HttpStatus.NOT_FOUND, response.getStatusCode());
        assertNull(response.getBody());

        verify(productRepository).findById(-1L);
    }

}