
// ********RoostGPT********
/*
Test generated by RoostGPT for test hebrew-unit-test using AI Type Claude AI and AI Model claude-3-5-sonnet-20241022

ROOST_METHOD_HASH=getPrice_b54117587b
ROOST_METHOD_SIG_HASH=getPrice_d2cb73a47d

                                            תרחיש 1: בדיקת החזרת מחיר חיובי תקין

                                                                          פרטים:
                                                שם הבדיקה: getPricePositiveValue
                       תיאור: בדיקת החזרת ערך מחיר חיובי תקין מהמתודה getPrice()

                                                                          ביצוע:
                               הכנה: יצירת אובייקט Product חדש והגדרת מחיר חיובי
                                                  פעולה: קריאה למתודה getPrice()
                                      בדיקה: וידוא שהערך המוחזר זהה למחיר שהוגדר

                                                                          אימות:
                הבדיקה מוודאת שהמתודה מחזירה את ערך המחיר המדויק שהוגדר באובייקט
                               חשיבות הבדיקה בהבטחת דיוק בהחזרת נתוני מחיר המוצר


*/

// ********RoostGPT********

package com.bootexample4.products.model;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Tag;
import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.*;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;

class ProductGetPriceTest {

	private Product product;

	@BeforeEach
	void setUp() {
		product = new Product();
	}

	@Test
	@Tag("valid")
	void getPricePositiveValue() {
		// Arrange
		double expectedPrice = 99.99;
		product.setPrice(expectedPrice);
		// Act
		double actualPrice = product.getPrice();
		// Assert
		assertEquals(expectedPrice, actualPrice, 0.001);
	}

	@Test
	@Tag("boundary")
	void getPriceZeroValue() {
		// Arrange
		double expectedPrice = 0.0;
		product.setPrice(expectedPrice);
		// Act
		double actualPrice = product.getPrice();
		// Assert
		assertEquals(expectedPrice, actualPrice, 0.001);
	}

	@Test
	@Tag("boundary")
	void getPriceMaxValue() {
		// Arrange
		double expectedPrice = Double.MAX_VALUE;
		product.setPrice(expectedPrice);
		// Act
		double actualPrice = product.getPrice();
		// Assert
		assertEquals(expectedPrice, actualPrice, 0.001);
	}

	@Test
	@Tag("boundary")
	void getPriceMinValue() {
		// Arrange
		double expectedPrice = Double.MIN_VALUE;
		product.setPrice(expectedPrice);
		// Act
		double actualPrice = product.getPrice();
		// Assert
		assertEquals(expectedPrice, actualPrice, 0.001);
	}

	@Test
	@Tag("valid")
	void getPricePrecisionCheck() {
		// Arrange
		double expectedPrice = 123.456789;
		product.setPrice(expectedPrice);
		// Act
		double actualPrice = product.getPrice();
		// Assert
		assertEquals(expectedPrice, actualPrice, 0.000001);
	}

}